apiVersion: v1
kind: ReplicationController
metadata:
  name: dronerc
  labels:
    name: dronerc
spec:
  replicas: 1
  selector:
    name: drone
  template:
    metadata:
      labels:
        name: drone
    spec:
      containers:
      - name: drone
        image: ipedrazas/drone:ubuntu
        ports:
        - containerPort: 8080
