apiVersion: v1
kind: Service
metadata:
  name: dronesvc
  labels:
    name: dronesvc
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8080
  selector:
    name: drone
